### ISSUE TITLE
Docs: Document that !important is ignored in keyframes

### ISSUE THREAD

**Issue by thecalamiity** [eslint/css#146]
### Rule details

Disallow invalid !important within keyframe declarations

### What type of rule is this?

Warns about a potential problem

### Example code

```css
@keyframes foo {
    from {
      opacity: 0;
    }
    to {
      opacity: 1 !important;
    }
}
```

### Participation

- [x] I am willing to submit a pull request to implement this rule.

### Additional comments

Declarations in a keyframe qualified with !important are ignored.

Corresponding stylelint rule - https://stylelint.io/user-guide/rules/keyframe-declaration-no-important/
