### ISSUE TITLE
New Rule: function-no-unknown

### ISSUE THREAD

**Issue by SwetaTanwar** [eslint/css#147]
### Rule details

Disallow unknown functions.

### What type of rule is this?

Warns about a potential problem

### Example code

```css
The following patterns are considered problems:


a { transform: unknown(1); }


The following patterns are not considered problems:


a { transform: scale(1); }



a { transform: --custom-function(1); }
```

### Participation

- [x] I am willing to submit a pull request to implement this rule.

### Additional comments

Prior Art: https://stylelint.io/user-guide/rules/function-no-unknown/
