### ISSUE TITLE
New Rule: `require-fallback-fonts`

### ISSUE THREAD

**Issue by Tanujkanti4441** [eslint/css#153]
### Rule details

Rule will enforce the use of fallback font to maintain consistency and readability across different devices and browsers.

### What type of rule is this?

Warns about a potential problem

### Example code

```css
body {
  font-family: "Open Sans";
}
```

### Participation

- [x] I am willing to submit a pull request to implement this rule.
