### ISSUE TITLE
Change Request: make `customSyntax` support directive objects (including Tailwind CSS v4 support)

### ISSUE THREAD

**Issue by OlivierZal** [eslint/css#55]
### Environment

ESLint version: 9.20.0
@eslint/css version: 0.3.0
Node version: 22.14.0
npm version: 11.1.0
Operating System: N/A

### What problem do you want to solve?

`customSyntax` can easily support Tailwind CSS v3 (thanks to `tailwindSyntax`) but would need some adjustments to support [Tailwind CSS v4](https://tailwindcss.com/docs/functions-and-directives#config-directive), since it doesn't only support `@apply` and `@config` directives (`@tailwind` is deprecated), but also:
  - [`@theme`](https://tailwindcss.com/blog/tailwindcss-v4#theme-directive)
  - [`@source`](https://tailwindcss.com/blog/tailwindcss-v4#source-directive)
  - [`@utility`](https://tailwindcss.com/blog/tailwindcss-v4#utility-directive)
  - [`@variant`](https://tailwindcss.com/blog/tailwindcss-v4#variant-directive)
  - [`@custom-variant`](https://tailwindcss.com/blog/tailwindcss-v4#custom-variant-directive)
  - [`@reference`](https://tailwindcss.com/blog/tailwindcss-v4#reference-directive)
  - [`@plugin`](https://tailwindcss.com/blog/tailwindcss-v4#plugin-directive)

These directives can be easily configured in `customSyntax`, e.g.:

```js
  {
    languageOptions: {
      customSyntax: {
        atrules: {
          plugin: {
            prelude: '<string>'
          },
          theme: {
            prelude: ''
          }
        }
      }
    }
  }
```

but the `atrules` option misses a way to avoid errors when the directives require an object, e.g.:

```css
/* no `no-invalid-at-rules` error thanks to the previous config */
@plugin 'daisyui' {
  /* raises a `no-invalid-at-rules` error after the prelude (as far as I know, with the current options) */
  themes: false;
}

@theme {
  /* raises a `no-invalid-at-rules` error after the prelude (as far as I know, with the current options) */
  --color-blue: var(--homey-text-color-blue);
  --color-color: var(--homey-text-color);
  --color-danger: var(--homey-text-color-danger);
  --color-light: var(--homey-text-color-light);

  --font-display: 'Roboto', 'sans-serif';

  --font-weight-bold: var(--homey-font-weight-bold);
  --font-weight-medium: var(--homey-font-weight-medium);
  --font-weight-normal: var(--homey-font-weight-regular);

  --text-default: var(--homey-font-size-default);
  --text-default--line-height: var(--homey-line-height-default);
}
```

### What do you think is the correct solution?

Would be great to be able to configure if a JSON is required after the prelude of a given directive, and to precise which keys (with regex support) are accepted, e.g.:

```js
  {
    languageOptions: {
      customSyntax: {
        atrules: {
          plugin: {
            prelude: '<string>',
            // undefined | false | true (no key constraint) | string[] (list of the accepted key regex)
            object: [
              '^themes$'
            ]
          },
          theme: {
            prelude: '',
            object: [
              '^--color-',
              '^--font-display$',
              '^--font-weight-'
            ]
          }
        }
      }
    }
  }
```

Even greater:
- having a `tailwind4Syntax` pre-set, given that available directives and [theme variable namespaces](https://tailwindcss.com/docs/theme#theme-variable-namespaces) are known
- being able to specify the accepted variables for each key:

```js
  {
    languageOptions: {
      customSyntax: {
        atrules: {
          plugin: {
            prelude: '<string>'
            object: {
              '^themes$': '<boolean>'
            }
          },
          theme: {
            prelude: ''
            object: {
              '^--color-': '<string>',
              '^--font-display$': '<string>[]',
              '^--font-weight-': '<number>'
            }
          }
        }
      }
    }
  }
```

### Participation

- [ ] I am willing to submit a pull request for this change.
