### ISSUE TITLE
New Rule: color-function-notation

### ISSUE THREAD

**Issue by azat-io** [eslint/css#76]
### Rule details

Specify modern or legacy notation for color-functions.

### What type of rule is this?

Warns about a potential problem

### Example code

There are two ways to set color notation.

Legacy:

```css
.test {
  color: rgba(12, 122, 231, 0.2);
  background: oklch(0, 0, 0);
}
```

Modern:

```css
.test {
  color: rgba(12 122 231 / 0.2);
  background: oklch(0 0 0);
}
```

I think it would be good to have a rule to check this.

```js
{
  rules: {
    'color-function-notation': ['error', 'modern'],
  },
}
```

### Participation

- [x] I am willing to submit a pull request to implement this rule.
