### ISSUE TITLE
Bug: Property 'outline' is not a widely available baseline feature

### ISSUE THREAD

**Issue by es-kim** [eslint/css#77]
### Environment

ESLint version: v9.21.0
@eslint/css version: ^0.4.0
Node version: v22.11.0
npm version: v10.9.0
Operating System: darwin 23.6.0

### Which language are you using?

stylesheet

### What did you do?

<details>
<summary>Configuration</summary>

```
{
  files: ['**/*.css'],
  language: 'css/css',
  ...css.configs.recommended,
},
```
</details>

```css
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}

div {
  outline: 4px auto -webkit-focus-ring-color;
}

a {
  outline: 4px auto -webkit-focus-ring-color;
}
```

### What did you expect to happen?

No error thrown for property 'outline'

### What actually happened?

Getting the following error in css file:
`Property 'outline' is not a widely available baseline feature`

Is the `outline` property not considered baseline? (Sorry if this isn't a bug as I'm new to Baseline)
https://github.com/web-platform-dx/web-features/blob/main/features/outline.yml

# Steps to Reproduce
1. Clone https://github.com/rviscomi/baseline-demos

2. In `eslint/`, run:

```bash
npm i
```

3. Update `eslint/eslint.config.mjs` file with below:

```js
import css from '@eslint/css';

export default [
  {
    files: ['**/*.css'],
    language: 'css/css',
    ...css.configs.recommended,
  },
];
```

4. See error in `eslint/src/test.css`, `line 35`:

```css
.container:has(.card:hover) {
  outline: 2px solid rebeccapurple;
}
```

### Link to Minimal Reproducible Example

See above for STR

### Participation

- [ ] I am willing to submit a pull request for this issue.
